import math

WIDTH = 640
HEIGHT = 360
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

MAP_SCALE = 40

PLAYER_POSITION = (1.5, 1.5) #minimapa
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.2
PLAYER_ROTATION_SPEED = 0.12
PLAYER_SIZE_SCALE = 2.5

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)

SCALE = WIDTH // NUM_RAYS